### ISSUE TITLE
About the accuracy

### ISSUE THREAD

**Issue by xhan233** [ytaek-oh/daso#3]
Hi. Thanks for the great work here.

But I can't reproduce the result you reported in Table 2(Ours γu = 1/100 (reversed) N1 = 1500 M1 = 3000).I use the config in configs/cifar10/fixmatch_daso,and my command is `python main.py --config-file configs/cifar10/fixmatch_daso.yaml \
DATASET.CIFAR10.NUM_LABELED_HEAD 1500 DATASET.CIFAR10.NUM_UNLABELED_HEAD 3000 DATASET.REVERSE_UL_DISTRIBUTION True`

The result I get in result.json is around 77.9,three points lower than your result.

**Comment by ytaek-oh** [comment]
Hello, thanks for your interest in our work, and sorry for your inconvenience.

That seems to be affected by different random seeds. 
Setting the random seed to 5491305 should give 81.08 in top1_median20 accuracy.

Please note that we fixed the random seeds across different methods for comparison.
Following table represents the results with the single fixed seed to 5491305.

CIFAR10 |   |  
-- | -- | --
SEED 5491305 | 500 / rev100 | 1500 / rev100
FixMatch | 62.11 | 73.79
DARP | 70.21 | 81
CReST | 72 | 81.05
DASO | 70.78 | 81.08


If any issue remains, please leave follow-up comments below.

Best Regards,
